name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - 3.8

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo xargs -a apt-packages.txt apt-get install --fix-missing

    - name: Download nltk corpus
      run: ././download-nltk-corpus.sh

    - name: Add User permissions
      run: sudo chmod -R 777 ./src/nltk/nltk

    - name: Run Tests
      run: make test
